export const handleError = (error) => {
  throw new Error(503);
};
